# Generated by Django 5.2.3 on 2026-01-20 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_avatar_remove_user_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('tool', models.CharField(choices=[('gpt-image', 'GPT Image'), ('nano-banana', 'Nano Banana'), ('seedream', 'Seedream'), ('flux', 'Flux'), ('z-image', 'Z-Image'), ('qwen', 'Qwen')], max_length=20)),
                ('model_id', models.CharField(max_length=200)),
                ('credits_used', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('fal_request_id', models.CharField(blank=True, max_length=200, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
