# Generated by Django 5.2.3 on 2026-01-29 04:48

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_subscription_period_fields'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        # Note: payment_method was already renamed to payment_provider in migration 0005
        # Note: plan_type was already renamed to plan in migration 0005
        migrations.RenameIndex(
            model_name='credithold',
            new_name='accounts_cr_user_id_ed7812_idx',
            old_name='accounts_cr_user_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='credithold',
            new_name='accounts_cr_status_2f6be8_idx',
            old_name='accounts_cr_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='accounts_pa_user_id_618f05_idx',
            old_name='accounts_pa_user_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='accounts_pa_payment_193e2f_idx',
            old_name='accounts_pa_payment_status_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='accounts_pa_created_c3fc2c_idx',
            old_name='accounts_pa_created_idx',
        ),
        # Note: credits_granted, credits_used_this_period, end_date were already removed in migration 0005
        # Note: next_renewal_date was already added in migration 0005 (renamed from end_date)
        migrations.AlterField(
            model_name='creditpurchase',
            name='package',
            field=models.CharField(choices=[('small', 'Top-up S - ₼10 - 450 kredit'), ('medium', 'Top-up M - ₼25 - 1,150 kredit'), ('large', 'Top-up L - ₼50 - 2,200 kredit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
