# Generated by Django 5.2.3 on 2026-01-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_old_subscription_fields'),
    ]

    operations = [
        # Note: credits_granted, credits_used_this_period, end_date, payment_method
        # were already removed in migration 0014_remove_old_subscription_fields
        # Only alter user.credits default value
        migrations.AlterField(
            model_name='user',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
