# Generated by Django 5.2.3 on 2026-02-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_fix_model_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogeneration',
            name='tool',
            field=models.CharField(choices=[('pika', 'Pika Labs'), ('seedance', 'Seedance'), ('wan', 'Wan'), ('luma', 'Luma AI'), ('kling', 'Kling AI'), ('veo', 'Veo'), ('sora', 'Sora'), ('sora-i2v', 'Sora (Image-to-Video)'), ('veo-i2v', 'Veo (Image-to-Video)'), ('kling-i2v', 'Kling AI (Image-to-Video)'), ('luma-i2v', 'Luma Photon (Image-to-Video)'), ('seedance-i2v', 'Seedance (Image-to-Video)'), ('pika-i2v', 'Pika Labs (Image-to-Video)'), ('gpt-image-i2v', 'GPT Image (Image-to-Video)'), ('nano-banana-i2v', 'Nano Banana (Image-to-Video)'), ('seedream-i2v', 'Seedream (Image-to-Video)'), ('flux-i2v', 'Flux (Image-to-Video)'), ('z-image-i2v', 'Z-Image (Image-to-Video)'), ('qwen-i2v', 'Qwen (Image-to-Video)')], max_length=20),
        ),
    ]
